pc - use database_url instead of jdbc_database_url
ucsb-cs156/proj-courses pull request #84
Opened 2024-03-28 05:27 UTC by pconrad

In this PR, we try using DATABASE_URL instead of JDBC_DATABASE_URL for dokku.

2024-03-28 05:27 UTC, pconrad commented on src/main/resources/application-production.properties
> +spring.datasource.url=${DATABASE_URL}
```suggestion
spring.datasource.url=jdbc:${DATABASE_URL}
```

2024-04-23 20:04 UTC, bnieder approved these changes
LGTM

2024-04-23 20:05 UTC, bnieder requested changes
If you are going to do this, I wonder whether we might also need to update the documentation about these environment variables?

2024-04-23 20:06 UTC, bnieder commented
LGTM

2024-05-07 17:55 UTC, pconrad commented
Unnecessary... and would cause a lot of documentation to need to change.

2024-05-07 17:55 UTC, closed without merging